# Generated by Django 3.1.13 on 2023-07-26 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20230724_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sysmenus',
            name='component_name',
        ),
        migrations.RemoveField(
            model_name='sysmenus',
            name='route_name',
        ),
    ]
