# Generated by Django 3.1.13 on 2023-08-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20230726_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysmenus',
            name='route_path',
            field=models.CharField(default='', max_length=128, verbose_name='route_path'),
        ),
    ]
