# Generated by Django 3.1.13 on 2023-08-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20230828_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysRoleMenus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.CharField(max_length=128, verbose_name='角色ID')),
                ('menu_id', models.CharField(max_length=128, verbose_name='菜单ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '角色菜单关系表',
                'verbose_name_plural': '角色菜单关系表',
                'db_table': 'sys_role_menus',
            },
        ),
        migrations.DeleteModel(
            name='SysUserMenus',
        ),
    ]
