# Generated by Django 3.1.13 on 2023-08-30 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20230830_0829'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SysMenus',
            new_name='SysMenu',
        ),
        migrations.RenameModel(
            old_name='SysRoleMenus',
            new_name='SysRoleMenu',
        ),
        migrations.AlterModelTable(
            name='sysmenu',
            table='sys_menu',
        ),
        migrations.AlterModelTable(
            name='sysrolemenu',
            table='sys_role_menu',
        ),
    ]
