# Generated by Django 3.1.13 on 2023-09-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20230830_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sysrolepermission',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='sysrolepermission',
            name='update_time',
        ),
        migrations.AlterField(
            model_name='sysrolemenu',
            name='menu_id',
            field=models.IntegerField(verbose_name='菜单ID'),
        ),
        migrations.AlterField(
            model_name='sysrolemenu',
            name='role_id',
            field=models.IntegerField(verbose_name='角色ID'),
        ),
        migrations.AlterField(
            model_name='sysrolepermission',
            name='per_id',
            field=models.IntegerField(verbose_name='权限ID'),
        ),
        migrations.AlterField(
            model_name='sysrolepermission',
            name='role_id',
            field=models.IntegerField(verbose_name='角色ID'),
        ),
        migrations.AlterField(
            model_name='sysuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='sysuserrole',
            name='role_id',
            field=models.IntegerField(verbose_name='角色ID'),
        ),
        migrations.AlterField(
            model_name='sysuserrole',
            name='user_id',
            field=models.IntegerField(verbose_name='用户ID'),
        ),
    ]
